// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
using AccelByte.Sdk.Api.Dslogmanager.Model;
using AccelByte.Sdk.Api.Dslogmanager.Operation;
using AccelByte.Sdk.Api.Dslogmanager.Wrapper;
using AccelByte.Sdk.Core;

namespace AccelByte.Sdk.Api
{
    public static class DslogmanagerAdmin_OpExts
    {
        public static Dslogmanager.Model.ModelsServerLogs? Execute(
            this GetServerLogs.GetServerLogsBuilder builder,
            string namespace_,
            string podName
        )
        {
            GetServerLogs op = builder.Build(
                namespace_,
                podName
            );

            return ((Dslogmanager.Wrapper.Admin)builder.WrapperObject!).GetServerLogs(op);
        }
    }
}