#!/usr/bin/env bash

# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

# This code is generated by tool. DO NOT EDIT.

# Meta:
# - random seed: 512
# - template file: cli-test.j2

# Instructions:
# - Run the Justice SDK Mock Server first before running this script.

export AB_BASE_URL="http://127.0.0.1:8080"
export AB_CLIENT_ID="admin"
export AB_CLIENT_SECRET="admin"
export AB_NAMESPACE="test"
export AB_APP_NAME="UnitTest"

EXIT_CODE=0

eval_tap() {
  if [ $1 -eq 0 ]; then
    echo "ok $2 - $3"
  else
    EXIT_CODE=1
    echo "not ok $2 - $3"
    sed 's/^/# /g' $4
  fi
  rm -f $4
}

CLI_EXE="AccelByte.Sdk.Sample.Cli"
CLI_TOKEN_FILE="$(dirname "$(which $CLI_EXE)")/token.json"
TEMP_JSON_INPUT="input_json.json"
TEMP_FILE_UPLOAD="file_upload.bin"

echo "TAP version 13"
echo "1..16"

#- 1 Login
$CLI_EXE --op login --lt user --user user --pass user > test.out 2>&1
eval_tap $? 1 'Login' test.out

if [ $EXIT_CODE -ne 0 ]; then
  echo "Bail out! Login failed."
  exit $EXIT_CODE
fi

# echo "foo" > "$CLI_TOKEN_FILE"

#- 2 AdminListAchievements
$CLI_EXE \
    --sn achievement \
    --op AdminListAchievements \
    --namespace $AB_NAMESPACE \
    --limit '28' \
    --offset '95' \
    --sortBy 'listOrder' \
    > test.out 2>&1
eval_tap $? 2 'AdminListAchievements' test.out

#- 3 AdminCreateNewAchievement
# body param: body
echo '{"achievementCode": "47MdLOC3", "defaultLanguage": "ITeOcAWH", "description": {"5oJS4QVe": "L0DzHmC9", "gNrDtchu": "ZTYuChJ0", "p0hSuWyv": "h34hqR93"}, "goalValue": 0.34546332854312467, "hidden": true, "incremental": false, "lockedIcons": [{"slug": "yRtv7J2p", "url": "9B8hDBHH"}, {"slug": "YPYZ1gDw", "url": "zLMrW9kn"}, {"slug": "em2aAao4", "url": "0mgmCMIe"}], "name": {"j3XQ9WIn": "I718Uci3", "aoNeVsvh": "aFL2TZUU", "7fLMoBOE": "rRXJdzCB"}, "statCode": "nKRZowvY", "tags": ["h2XW6Xzt", "MZiG7Sa7", "IzOyLzFR"], "unlockedIcons": [{"slug": "TV0YtNVJ", "url": "8Fip2Amj"}, {"slug": "41Pwi1VO", "url": "cHVqt4qD"}, {"slug": "FfW8VvWK", "url": "lIU5Ay6i"}]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn achievement \
    --op AdminCreateNewAchievement \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 3 'AdminCreateNewAchievement' test.out

#- 4 ExportAchievements
$CLI_EXE \
    --sn achievement \
    --op ExportAchievements \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 4 'ExportAchievements' test.out

#- 5 ImportAchievements
# form data upload: file
echo 'tmp.dat' > $TEMP_FILE_UPLOAD
$CLI_EXE \
    --sn achievement \
    --op ImportAchievements \
    --namespace $AB_NAMESPACE \
    --upload $TEMP_FILE_UPLOAD \
    --strategy 'gOIs0C0E' \
    > test.out 2>&1
eval_tap $? 5 'ImportAchievements' test.out

#- 6 AdminGetAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminGetAchievement \
    --achievementCode 'dG32Gnfy' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 6 'AdminGetAchievement' test.out

#- 7 AdminUpdateAchievement
# body param: body
echo '{"defaultLanguage": "FHoauINd", "description": {"VEeIhAfO": "zTBlezQx", "NBtMafz2": "A5NX429O", "lC3aXX6c": "zLh8Qsu9"}, "goalValue": 0.8821902665127741, "hidden": false, "incremental": true, "lockedIcons": [{"slug": "oWjVHpvL", "url": "9PRwy4Wj"}, {"slug": "9YPpSFaM", "url": "WDZlaCbk"}, {"slug": "TF4seFO1", "url": "MtTLtxx9"}], "name": {"JKZEbwK7": "78Dg3Gx9", "OYiPJ9uV": "nXmy31ts", "rNpExBuE": "qKy9cY68"}, "statCode": "ALgY9cof", "tags": ["nHo9f4oG", "MgQ1Nzbj", "ybTH43VR"], "unlockedIcons": [{"slug": "QzPIg3nw", "url": "8YqNUMKc"}, {"slug": "NQKfJncG", "url": "c0VgNLt6"}, {"slug": "E9IHtus4", "url": "bNz1p2dj"}]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn achievement \
    --op AdminUpdateAchievement \
    --achievementCode 'mv3NshFZ' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 7 'AdminUpdateAchievement' test.out

#- 8 AdminDeleteAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminDeleteAchievement \
    --achievementCode '6BjFPeKY' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 8 'AdminDeleteAchievement' test.out

#- 9 AdminUpdateAchievementListOrder
# body param: body
echo '{"targetOrder": 10}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn achievement \
    --op AdminUpdateAchievementListOrder \
    --achievementCode 'fu91kc9y' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 9 'AdminUpdateAchievementListOrder' test.out

#- 10 AdminListUserAchievements
$CLI_EXE \
    --sn achievement \
    --op AdminListUserAchievements \
    --namespace $AB_NAMESPACE \
    --userId '3MLzOHNP' \
    --limit '85' \
    --offset '67' \
    --preferUnlocked 'false' \
    > test.out 2>&1
eval_tap $? 10 'AdminListUserAchievements' test.out

#- 11 AdminResetAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminResetAchievement \
    --achievementCode 'Wf3CmHgb' \
    --namespace $AB_NAMESPACE \
    --userId '0nugKjuY' \
    > test.out 2>&1
eval_tap $? 11 'AdminResetAchievement' test.out

#- 12 AdminUnlockAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminUnlockAchievement \
    --achievementCode '7RY99xL3' \
    --namespace $AB_NAMESPACE \
    --userId '6grW1JCY' \
    > test.out 2>&1
eval_tap $? 12 'AdminUnlockAchievement' test.out

#- 13 PublicListAchievements
$CLI_EXE \
    --sn achievement \
    --op PublicListAchievements \
    --namespace $AB_NAMESPACE \
    --limit '63' \
    --offset '81' \
    --sortBy 'createdAt:desc' \
    --language 'PRMleAxt' \
    > test.out 2>&1
eval_tap $? 13 'PublicListAchievements' test.out

#- 14 PublicGetAchievement
$CLI_EXE \
    --sn achievement \
    --op PublicGetAchievement \
    --achievementCode '8Il0ltZd' \
    --namespace $AB_NAMESPACE \
    --language 'tRBIXdBI' \
    > test.out 2>&1
eval_tap $? 14 'PublicGetAchievement' test.out

#- 15 PublicListUserAchievements
$CLI_EXE \
    --sn achievement \
    --op PublicListUserAchievements \
    --namespace $AB_NAMESPACE \
    --userId 'YA2cOPQi' \
    --limit '61' \
    --offset '73' \
    --preferUnlocked 'false' \
    > test.out 2>&1
eval_tap $? 15 'PublicListUserAchievements' test.out

#- 16 PublicUnlockAchievement
$CLI_EXE \
    --sn achievement \
    --op PublicUnlockAchievement \
    --achievementCode 'USjCJm22' \
    --namespace $AB_NAMESPACE \
    --userId 'r1h8vhaa' \
    > test.out 2>&1
eval_tap $? 16 'PublicUnlockAchievement' test.out


# remove artifacts
rm -f "$CLI_TOKEN_FILE"
rm -f "$TEMP_JSON_INPUT"
rm -f "$TEMP_FILE_UPLOAD"

exit $EXIT_CODE