#!/usr/bin/env bash

# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

# This code is generated by tool. DO NOT EDIT.

# Meta:
# - random seed: 512
# - template file: cli-test.j2

# Instructions:
# - Run the Justice SDK Mock Server first before running this script.

export AB_BASE_URL="http://127.0.0.1:8080"
export AB_CLIENT_ID="admin"
export AB_CLIENT_SECRET="admin"
export AB_NAMESPACE="test"
export AB_APP_NAME="UnitTest"

EXIT_CODE=0

eval_tap() {
  if [ $1 -eq 0 ]; then
    echo "ok $2 - $3"
  else
    EXIT_CODE=1
    echo "not ok $2 - $3"
    sed 's/^/# /g' $4
  fi
  rm -f $4
}

CLI_EXE="AccelByte.Sdk.Sample.Cli"
CLI_TOKEN_FILE="$(dirname "$(which $CLI_EXE)")/token.json"
TEMP_JSON_INPUT="input_json.json"
TEMP_FILE_UPLOAD="file_upload.bin"

echo "TAP version 13"
echo "1..27"

#- 1 Login
$CLI_EXE --op login --lt user --user user --pass user > test.out 2>&1
eval_tap $? 1 'Login' test.out

if [ $EXIT_CODE -ne 0 ]; then
  echo "Bail out! Login failed."
  exit $EXIT_CODE
fi

# echo "foo" > "$CLI_TOKEN_FILE"

#- 2 AdminListAchievements
$CLI_EXE \
    --sn achievement \
    --op AdminListAchievements \
    --namespace $AB_NAMESPACE \
    --global 'false' \
    --limit '56' \
    --offset '18' \
    --sortBy 'createdAt:desc' \
    --tags '["3wMWnoZgIhwb8YYM", "LqpQwkRRHkaiKsmI", "iRLR3IlNJKxhPfWV"]' \
    > test.out 2>&1
eval_tap $? 2 'AdminListAchievements' test.out

#- 3 AdminCreateNewAchievement
# body param: body
echo '{"achievementCode": "6dIabcFbSmeuIBro", "customAttributes": {"F7bwRgwKvzESbhpx": {}, "lDdEs4igdKeLmy8t": {}, "Z5GZi5P12c61ts3f": {}}, "defaultLanguage": "MI04rm2jUc9iav3t", "description": {"TqlE9oLDPD0Lfle8": "ESU1MO8XnVaEyjmi", "fJDYa1TJPUszmFGE": "kJVvqDSU3PDyIAGf", "Gq1FNmRWvUvDPnKo": "ECjGUg867xodwuG1"}, "global": true, "goalValue": 0.8491560886251529, "hidden": false, "incremental": true, "lockedIcons": [{"slug": "6s9p8Y5c9eItJtiN", "url": "mY3y3n2Rim4NBqhu"}, {"slug": "Ntj8FOvKZjs1tLpE", "url": "Rf77LzPoORBkRmZ0"}, {"slug": "A2zyZsb4FvWFIHPI", "url": "bOjpls9BZTYc5Bsd"}], "name": {"SSVaAzzn4GbgkKeC": "aS6qyUCscHXs8PlO", "BlfUOqv7WmCuqcsN": "M7YAnbq4DjmYUMhD", "9qU89D356pVsUtNa": "nddzgwxYdQc5hEfe"}, "statCode": "fdopcEM0JHfof2Hw", "tags": ["i7vg3osbh0fL2h7e", "JvAS2W4uqkhwSC7E", "ajwHO3LfvwPewrf1"], "unlockedIcons": [{"slug": "9Njm50xCDlPeNq0C", "url": "vMXtyUWXrdZaFeac"}, {"slug": "GT2x6o28Njxyw7RH", "url": "ldq0m7NjUZ95Z5XD"}, {"slug": "LBN9YGVPtkjt0OyB", "url": "lJi4RbZ0Iy11mfOF"}]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn achievement \
    --op AdminCreateNewAchievement \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 3 'AdminCreateNewAchievement' test.out

#- 4 ExportAchievements
$CLI_EXE \
    --sn achievement \
    --op ExportAchievements \
    --namespace $AB_NAMESPACE \
    --tags '["jCzZVcGomWF1oAqU", "NFDtXnXLvOAsW8wY", "h4gq7pRVZVLJiDx3"]' \
    > test.out 2>&1
eval_tap $? 4 'ExportAchievements' test.out

#- 5 ImportAchievements
# form data upload: file
echo 'tmp.dat' > $TEMP_FILE_UPLOAD
$CLI_EXE \
    --sn achievement \
    --op ImportAchievements \
    --namespace $AB_NAMESPACE \
    --upload file $TEMP_FILE_UPLOAD \
    --strategy 'au9b9QjhzDlnJmi4' \
    > test.out 2>&1
eval_tap $? 5 'ImportAchievements' test.out

#- 6 AdminGetAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminGetAchievement \
    --achievementCode 'XaBTgoXjfdUQHa3R' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 6 'AdminGetAchievement' test.out

#- 7 AdminUpdateAchievement
# body param: body
echo '{"customAttributes": {"xspSqwdbTR2sgzfa": {}, "QrUCW9fgo69uv1bk": {}, "Fx8DmbC9UqYdYrdx": {}}, "defaultLanguage": "NnuMcAwrSzYnrcet", "description": {"xObeisZelKuD0iJ6": "fs3zL9H4WxGWRH7f", "z4BdPhLtHRJOImSq": "37aeAaGq0NIj53gX", "kmrayvcIYiWxIAxf": "vLzSpDFY3lxe16Ks"}, "global": true, "goalValue": 0.06600199760567105, "hidden": true, "incremental": false, "lockedIcons": [{"slug": "PYQ5yVcQuvDbGMqb", "url": "EHkCQwMBcQUNPHN8"}, {"slug": "YZT0yJJ0uCjjaNCR", "url": "V3hSIiTEoTCSxjAq"}, {"slug": "g9oGVEdC8mQir1Af", "url": "0G6OrPH6ZsjpPgHK"}], "name": {"ISHtB8tWdJM9Qc5H": "mR0vknXO45AUtNXS", "TItt35OJTfJBZX62": "yI9g5RDrlzPFQmNu", "3ERxV0UTaiSzfi0F": "nBERe8qNYRTYSaZw"}, "statCode": "4NqSNylcljuNM3eU", "tags": ["USD1pZGMfPdGIOAZ", "86un0L98WUoXvfU4", "qMIpfgxw2ff5twRY"], "unlockedIcons": [{"slug": "btdK2r4wWs6IpYBx", "url": "afo9b4xJyNnvHKrm"}, {"slug": "8UuNlT86N9yO0vyD", "url": "6J5brVo20e6POTjr"}, {"slug": "inAVVovpAAXNzcpb", "url": "mX3lLFeXCiaXP8jB"}]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn achievement \
    --op AdminUpdateAchievement \
    --achievementCode 'jK81t2V9TVauFcGk' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 7 'AdminUpdateAchievement' test.out

#- 8 AdminDeleteAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminDeleteAchievement \
    --achievementCode 'PgQ0hb2tLrsMeoZi' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 8 'AdminDeleteAchievement' test.out

#- 9 AdminUpdateAchievementListOrder
# body param: body
echo '{"targetOrder": 90}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn achievement \
    --op AdminUpdateAchievementListOrder \
    --achievementCode 'ztr2QcwlRrReRajl' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 9 'AdminUpdateAchievementListOrder' test.out

#- 10 AdminListGlobalAchievements
$CLI_EXE \
    --sn achievement \
    --op AdminListGlobalAchievements \
    --namespace $AB_NAMESPACE \
    --achievementCodes 'pk8lfuiJVcktlx9z' \
    --limit '73' \
    --offset '0' \
    --sortBy 'ZVVCc9bpIHEWQMmC' \
    --status 'kIqwqpoTVCNrcaVo' \
    --tags '["zsjIXO2EUsAfBvo6", "Llcalks2R3VMtipT", "VxXAF8KhOKqbrECi"]' \
    > test.out 2>&1
eval_tap $? 10 'AdminListGlobalAchievements' test.out

#- 11 AdminListGlobalAchievementContributors
$CLI_EXE \
    --sn achievement \
    --op AdminListGlobalAchievementContributors \
    --achievementCode 'jFxOpOzxeTLJQsZc' \
    --namespace $AB_NAMESPACE \
    --limit '93' \
    --offset '62' \
    --sortBy 'hPPG5sAIfYtYozA2' \
    > test.out 2>&1
eval_tap $? 11 'AdminListGlobalAchievementContributors' test.out

#- 12 ResetGlobalAchievement
$CLI_EXE \
    --sn achievement \
    --op ResetGlobalAchievement \
    --achievementCode 'OntGCwQSHHdPLwjT' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 12 'ResetGlobalAchievement' test.out

#- 13 AdminListTags
$CLI_EXE \
    --sn achievement \
    --op AdminListTags \
    --namespace $AB_NAMESPACE \
    --limit '27' \
    --name 'D9oYwS8oLyErKvRt' \
    --offset '70' \
    --sortBy 'YjR7c4x5bIk8pVpx' \
    > test.out 2>&1
eval_tap $? 13 'AdminListTags' test.out

#- 14 AdminListUserAchievements
$CLI_EXE \
    --sn achievement \
    --op AdminListUserAchievements \
    --namespace $AB_NAMESPACE \
    --userId 'dUWOPel3TiwTycqp' \
    --limit '98' \
    --offset '40' \
    --preferUnlocked 'false' \
    --sortBy '2OVBTLwSH8hWRU9p' \
    --tags '["bItGQ7VUWBhGolwa", "fIfbF1GLFnrQ4T5c", "mw7U1TxiS06UEoaD"]' \
    > test.out 2>&1
eval_tap $? 14 'AdminListUserAchievements' test.out

#- 15 AdminResetAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminResetAchievement \
    --achievementCode 'ZpXOWzpXOi2cpajt' \
    --namespace $AB_NAMESPACE \
    --userId 'qcXjPkj2IzU3MEpC' \
    > test.out 2>&1
eval_tap $? 15 'AdminResetAchievement' test.out

#- 16 AdminUnlockAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminUnlockAchievement \
    --achievementCode 't1IjlfHJM92t9j1X' \
    --namespace $AB_NAMESPACE \
    --userId 'T2ErwIxkaTnYtr1Y' \
    > test.out 2>&1
eval_tap $? 16 'AdminUnlockAchievement' test.out

#- 17 AdminAnonymizeUserAchievement
$CLI_EXE \
    --sn achievement \
    --op AdminAnonymizeUserAchievement \
    --namespace $AB_NAMESPACE \
    --userId 'DnaXB0JOS4XKVT66' \
    > test.out 2>&1
eval_tap $? 17 'AdminAnonymizeUserAchievement' test.out

#- 18 AdminListUserContributions
$CLI_EXE \
    --sn achievement \
    --op AdminListUserContributions \
    --namespace $AB_NAMESPACE \
    --userId 'sHYPgVsfhoEidKw4' \
    --achievementCodes 'IP0NVnaangorhVFp' \
    --limit '94' \
    --offset '88' \
    --sortBy 'RuQyMroT2hNfKJ7q' \
    --tags '["8sifSPmYSsBxtyKW", "ssEn5VEvIMEB4pl5", "06fLCG6EAl7d3Ks6"]' \
    > test.out 2>&1
eval_tap $? 18 'AdminListUserContributions' test.out

#- 19 PublicListAchievements
$CLI_EXE \
    --sn achievement \
    --op PublicListAchievements \
    --namespace $AB_NAMESPACE \
    --global 'true' \
    --limit '14' \
    --offset '15' \
    --sortBy 'listOrder' \
    --tags '["tnjcMSw1J42fthKU", "obas2CAlSxxVhDR9", "hlaznetBUGcQz2Wv"]' \
    --language 'diclkYGDL2ckC9cd' \
    > test.out 2>&1
eval_tap $? 19 'PublicListAchievements' test.out

#- 20 PublicGetAchievement
$CLI_EXE \
    --sn achievement \
    --op PublicGetAchievement \
    --achievementCode 'zaLnajQ8GnJpALid' \
    --namespace $AB_NAMESPACE \
    --language 'dv9UUtG1tEECsm8x' \
    > test.out 2>&1
eval_tap $? 20 'PublicGetAchievement' test.out

#- 21 PublicListGlobalAchievements
$CLI_EXE \
    --sn achievement \
    --op PublicListGlobalAchievements \
    --namespace $AB_NAMESPACE \
    --achievementCodes 'aDOz0tMlpFuJVXo9' \
    --limit '39' \
    --offset '63' \
    --sortBy '0JPG8cgjHQo9HoLL' \
    --status 'yUnPTiCD0038or8w' \
    --tags '["R0tuwIJnrSI2IFcR", "wSoMTuJziuDNbOyd", "iu3lOaruuYw0iUut"]' \
    > test.out 2>&1
eval_tap $? 21 'PublicListGlobalAchievements' test.out

#- 22 ListGlobalAchievementContributors
$CLI_EXE \
    --sn achievement \
    --op ListGlobalAchievementContributors \
    --achievementCode 's6bChMK1gcx8p9fy' \
    --namespace $AB_NAMESPACE \
    --limit '44' \
    --offset '24' \
    --sortBy '5PoMJeTIQix1FEvz' \
    > test.out 2>&1
eval_tap $? 22 'ListGlobalAchievementContributors' test.out

#- 23 PublicListTags
$CLI_EXE \
    --sn achievement \
    --op PublicListTags \
    --namespace $AB_NAMESPACE \
    --limit '23' \
    --name 'S2OZZfXO3HkJTOPs' \
    --offset '6' \
    --sortBy 'AopmjI7CbY2WuwRU' \
    > test.out 2>&1
eval_tap $? 23 'PublicListTags' test.out

#- 24 PublicListUserAchievements
$CLI_EXE \
    --sn achievement \
    --op PublicListUserAchievements \
    --namespace $AB_NAMESPACE \
    --userId 'T9IivgC4mJ5OHuNE' \
    --limit '97' \
    --offset '6' \
    --preferUnlocked 'true' \
    --sortBy 'K4Mvk00I9GqAhhjN' \
    --tags '["IivdIcaEQfNETQCB", "PK1mYwKVQoydbYjX", "ZyBpqhCJBtFOm3iC"]' \
    > test.out 2>&1
eval_tap $? 24 'PublicListUserAchievements' test.out

#- 25 PublicUnlockAchievement
$CLI_EXE \
    --sn achievement \
    --op PublicUnlockAchievement \
    --achievementCode 'pu0lhhgutt3rQuKP' \
    --namespace $AB_NAMESPACE \
    --userId '1OEtKFBjNihHU8GP' \
    > test.out 2>&1
eval_tap $? 25 'PublicUnlockAchievement' test.out

#- 26 ListUserContributions
$CLI_EXE \
    --sn achievement \
    --op ListUserContributions \
    --namespace $AB_NAMESPACE \
    --userId '8TRVypSvYXKz4BGj' \
    --achievementCodes 'bsrRBV8aztJ86yQK' \
    --limit '54' \
    --offset '38' \
    --sortBy 'hOhenJi6dNVF7zwj' \
    --tags '["XqlcD2LzaOwIF5tE", "sCwoAVcZCSj80gzF", "vpvIerFEyxTugoTd"]' \
    > test.out 2>&1
eval_tap $? 26 'ListUserContributions' test.out

#- 27 ClaimGlobalAchievementReward
$CLI_EXE \
    --sn achievement \
    --op ClaimGlobalAchievementReward \
    --achievementCode '50RmJFX9v4GPfyGu' \
    --namespace $AB_NAMESPACE \
    --userId 'Q2UEl0U5Z9UnQmZq' \
    > test.out 2>&1
eval_tap $? 27 'ClaimGlobalAchievementReward' test.out


# remove artifacts
rm -f "$CLI_TOKEN_FILE"
rm -f "$TEMP_JSON_INPUT"
rm -f "$TEMP_FILE_UPLOAD"

exit $EXIT_CODE