#!/usr/bin/env bash

# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

# This code is generated by tool. DO NOT EDIT.

# Meta:
# - random seed: 512
# - template file: cli-test.j2

# Instructions:
# - Run the Justice SDK Mock Server first before running this script.

export AB_BASE_URL="http://127.0.0.1:8080"
export AB_CLIENT_ID="admin"
export AB_CLIENT_SECRET="admin"
export AB_NAMESPACE="test"
export AB_APP_NAME="UnitTest"

EXIT_CODE=0

eval_tap() {
  if [ $1 -eq 0 ]; then
    echo "ok $2 - $3"
  else
    EXIT_CODE=1
    echo "not ok $2 - $3"
    sed 's/^/# /g' $4
  fi
  rm -f $4
}

CLI_EXE="AccelByte.Sdk.Sample.Cli"
CLI_TOKEN_FILE="$(dirname "$(which $CLI_EXE)")/token.json"
TEMP_JSON_INPUT="input_json.json"
TEMP_FILE_UPLOAD="file_upload.bin"

echo "TAP version 13"
echo "1..92"

#- 1 Login
$CLI_EXE --op login --lt user --user user --pass user > test.out 2>&1
eval_tap $? 1 'Login' test.out

if [ $EXIT_CODE -ne 0 ]; then
  echo "Bail out! Login failed."
  exit $EXIT_CODE
fi

# echo "foo" > "$CLI_TOKEN_FILE"

#- 2 SingleAdminGetChannel
$CLI_EXE \
    --sn ugc \
    --op SingleAdminGetChannel \
    --namespace $AB_NAMESPACE \
    --limit '2' \
    --offset '56' \
    > test.out 2>&1
eval_tap $? 2 'SingleAdminGetChannel' test.out

#- 3 AdminCreateChannel
# body param: body
echo '{"name": "i3wMWnoZ"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminCreateChannel \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 3 'AdminCreateChannel' test.out

#- 4 SingleAdminUpdateChannel
# body param: body
echo '{"name": "gIhwb8YY"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op SingleAdminUpdateChannel \
    --channelId 'MLqpQwkR' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 4 'SingleAdminUpdateChannel' test.out

#- 5 SingleAdminDeleteChannel
$CLI_EXE \
    --sn ugc \
    --op SingleAdminDeleteChannel \
    --channelId 'RHkaiKsm' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 5 'SingleAdminDeleteChannel' test.out

#- 6 AdminUploadContentDirect
eval_tap 0 6 'AdminUploadContentDirect # SKIP deprecated' test.out

#- 7 AdminUploadContentS3
# body param: body
echo '{"contentType": "IiRLR3Il", "customAttributes": {"NJKxhPfW": {}, "V6dIabcF": {}, "bSmeuIBr": {}}, "fileExtension": "oF7bwRgw", "name": "KvzESbhp", "preview": "xlDdEs4i", "previewMetadata": {"previewContentType": "gdKeLmy8", "previewFileExtension": "tZ5GZi5P"}, "subType": "12c61ts3", "tags": ["fMI04rm2", "jUc9iav3", "tTqlE9oL"], "type": "DPD0Lfle"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminUploadContentS3 \
    --channelId '8ESU1MO8' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 7 'AdminUploadContentS3' test.out

#- 8 SingleAdminUpdateContentS3
# body param: body
echo '{"contentType": "XnVaEyjm", "customAttributes": {"ifJDYa1T": {}, "JPUszmFG": {}, "EkJVvqDS": {}}, "fileExtension": "U3PDyIAG", "name": "fGq1FNmR", "payload": "WvUvDPnK", "preview": "oECjGUg8", "previewMetadata": {"previewContentType": "67xodwuG", "previewFileExtension": "14ID5l5w"}, "subType": "j6K2wEMn", "tags": ["ckjlW6By", "wsSSZTGl", "ubsmhjXc"], "type": "ScOUvrjJ", "updateContentFile": true}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op SingleAdminUpdateContentS3 \
    --channelId 'js1tLpER' \
    --contentId 'f77LzPoO' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 8 'SingleAdminUpdateContentS3' test.out

#- 9 AdminSearchChannelSpecificContent
$CLI_EXE \
    --sn ugc \
    --op AdminSearchChannelSpecificContent \
    --channelId 'RBkRmZ0A' \
    --namespace $AB_NAMESPACE \
    --creator '2zyZsb4F' \
    --isofficial 'vWFIHPIb' \
    --limit '82' \
    --name '5fHdWqJT' \
    --offset '81' \
    --orderby 'Yc5BsdSS' \
    --sortby 'VaAzzn4G' \
    --subtype 'bgkKeCaS' \
    --tags '["6qyUCscH", "Xs8PlOBl", "fUOqv7Wm"]' \
    --type 'CuqcsNM7' \
    --userId 'YAnbq4Dj' \
    > test.out 2>&1
eval_tap $? 9 'AdminSearchChannelSpecificContent' test.out

#- 10 SingleAdminUpdateContentDirect
eval_tap 0 10 'SingleAdminUpdateContentDirect # SKIP deprecated' test.out

#- 11 SingleAdminDeleteContent
$CLI_EXE \
    --sn ugc \
    --op SingleAdminDeleteContent \
    --channelId 'mYUMhD9q' \
    --contentId 'U89D356p' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 11 'SingleAdminDeleteContent' test.out

#- 12 SingleAdminGetContent
$CLI_EXE \
    --sn ugc \
    --op SingleAdminGetContent \
    --namespace $AB_NAMESPACE \
    --limit '97' \
    --offset '11' \
    > test.out 2>&1
eval_tap $? 12 'SingleAdminGetContent' test.out

#- 13 AdminGetContentBulk
# body param: body
echo '{"contentIds": ["sUtNandd", "zgwxYdQc", "5hEfefdo"]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminGetContentBulk \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 13 'AdminGetContentBulk' test.out

#- 14 AdminSearchContent
$CLI_EXE \
    --sn ugc \
    --op AdminSearchContent \
    --namespace $AB_NAMESPACE \
    --creator 'pcEM0JHf' \
    --isofficial 'of2Hwi7v' \
    --limit '12' \
    --name 'RXJdoSTx' \
    --offset '81' \
    --orderby '2h7eJvAS' \
    --sortby '2W4uqkhw' \
    --subtype 'SC7EajwH' \
    --tags '["O3LfvwPe", "wrf19Njm", "50xCDlPe"]' \
    --type 'Nq0CvMXt' \
    --userId 'yUWXrdZa' \
    > test.out 2>&1
eval_tap $? 14 'AdminSearchContent' test.out

#- 15 AdminGetUserContentByShareCode
$CLI_EXE \
    --sn ugc \
    --op AdminGetUserContentByShareCode \
    --namespace $AB_NAMESPACE \
    --shareCode 'FeacGT2x' \
    > test.out 2>&1
eval_tap $? 15 'AdminGetUserContentByShareCode' test.out

#- 16 AdminGetSpecificContent
$CLI_EXE \
    --sn ugc \
    --op AdminGetSpecificContent \
    --contentId '6o28Njxy' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 16 'AdminGetSpecificContent' test.out

#- 17 AdminDownloadContentPreview
$CLI_EXE \
    --sn ugc \
    --op AdminDownloadContentPreview \
    --contentId 'w7RHldq0' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 17 'AdminDownloadContentPreview' test.out

#- 18 AdminUpdateScreenshots
# body param: body
echo '{"screenshots": [{"description": "m7NjUZ95", "screenshotId": "Z5XDLBN9"}, {"description": "YGVPtkjt", "screenshotId": "0OyBlJi4"}, {"description": "RbZ0Iy11", "screenshotId": "mfOFjCzZ"}]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminUpdateScreenshots \
    --contentId 'VcGomWF1' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 18 'AdminUpdateScreenshots' test.out

#- 19 AdminUploadContentScreenshot
# body param: body
echo '{"screenshots": [{"contentType": "oAqUNFDt", "description": "XnXLvOAs", "fileExtension": "jfif"}, {"contentType": "8wYh4gq7", "description": "pRVZVLJi", "fileExtension": "jpg"}, {"contentType": "l03vtlMF", "description": "zeiMRkcO", "fileExtension": "jpeg"}]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminUploadContentScreenshot \
    --contentId 'i4XaBTgo' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 19 'AdminUploadContentScreenshot' test.out

#- 20 AdminDeleteContentScreenshot
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteContentScreenshot \
    --contentId 'XjfdUQHa' \
    --namespace $AB_NAMESPACE \
    --screenshotId '3RxspSqw' \
    > test.out 2>&1
eval_tap $? 20 'AdminDeleteContentScreenshot' test.out

#- 21 SingleAdminGetAllGroups
$CLI_EXE \
    --sn ugc \
    --op SingleAdminGetAllGroups \
    --namespace $AB_NAMESPACE \
    --limit '7' \
    --offset '3' \
    > test.out 2>&1
eval_tap $? 21 'SingleAdminGetAllGroups' test.out

#- 22 AdminCreateGroup
# body param: body
echo '{"contents": ["m9K3cMY6", "17HSCYZa", "L46I3PgC"], "name": "cQ0axTWn"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminCreateGroup \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 22 'AdminCreateGroup' test.out

#- 23 SingleAdminGetGroup
$CLI_EXE \
    --sn ugc \
    --op SingleAdminGetGroup \
    --groupId 'myEYLZQT' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 23 'SingleAdminGetGroup' test.out

#- 24 SingleAdminUpdateGroup
# body param: body
echo '{"contents": ["pvLH6QPE", "BP8kSSFj", "euL3wQQP"], "name": "YwmYFbxR"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op SingleAdminUpdateGroup \
    --groupId 'vHYDCYwo' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 24 'SingleAdminUpdateGroup' test.out

#- 25 SingleAdminDeleteGroup
$CLI_EXE \
    --sn ugc \
    --op SingleAdminDeleteGroup \
    --groupId 'GdmzXgf1' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 25 'SingleAdminDeleteGroup' test.out

#- 26 SingleAdminGetGroupContents
$CLI_EXE \
    --sn ugc \
    --op SingleAdminGetGroupContents \
    --groupId 'ewUTvnu0' \
    --namespace $AB_NAMESPACE \
    --limit '10' \
    --offset '69' \
    > test.out 2>&1
eval_tap $? 26 'SingleAdminGetGroupContents' test.out

#- 27 AdminGetTag
$CLI_EXE \
    --sn ugc \
    --op AdminGetTag \
    --namespace $AB_NAMESPACE \
    --limit '28' \
    --offset '89' \
    > test.out 2>&1
eval_tap $? 27 'AdminGetTag' test.out

#- 28 AdminCreateTag
# body param: body
echo '{"tag": "sa3MZF7D"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminCreateTag \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 28 'AdminCreateTag' test.out

#- 29 AdminUpdateTag
# body param: body
echo '{"tag": "TswnkSyu"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminUpdateTag \
    --namespace $AB_NAMESPACE \
    --tagId 'JTVjKQ1O' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 29 'AdminUpdateTag' test.out

#- 30 AdminDeleteTag
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteTag \
    --namespace $AB_NAMESPACE \
    --tagId 'RLEIAePv' \
    > test.out 2>&1
eval_tap $? 30 'AdminDeleteTag' test.out

#- 31 AdminGetType
$CLI_EXE \
    --sn ugc \
    --op AdminGetType \
    --namespace $AB_NAMESPACE \
    --limit '60' \
    --offset '100' \
    > test.out 2>&1
eval_tap $? 31 'AdminGetType' test.out

#- 32 AdminCreateType
# body param: body
echo '{"subtype": ["O2xkVgyR", "k10b27Rd", "U8VceYQ9"], "type": "erPYQ5yV"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminCreateType \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 32 'AdminCreateType' test.out

#- 33 AdminUpdateType
# body param: body
echo '{"subtype": ["cQuvDbGM", "qbEHkCQw", "MBcQUNPH"], "type": "N8YZT0yJ"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminUpdateType \
    --namespace $AB_NAMESPACE \
    --typeId 'J0uCjjaN' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 33 'AdminUpdateType' test.out

#- 34 AdminDeleteType
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteType \
    --namespace $AB_NAMESPACE \
    --typeId 'CRV3hSIi' \
    > test.out 2>&1
eval_tap $? 34 'AdminDeleteType' test.out

#- 35 AdminGetChannel
$CLI_EXE \
    --sn ugc \
    --op AdminGetChannel \
    --namespace $AB_NAMESPACE \
    --userId 'TEoTCSxj' \
    --limit '53' \
    --offset '65' \
    > test.out 2>&1
eval_tap $? 35 'AdminGetChannel' test.out

#- 36 AdminDeleteAllUserChannels
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteAllUserChannels \
    --namespace $AB_NAMESPACE \
    --userId 'qg9oGVEd' \
    > test.out 2>&1
eval_tap $? 36 'AdminDeleteAllUserChannels' test.out

#- 37 AdminUpdateChannel
# body param: body
echo '{"name": "C8mQir1A"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminUpdateChannel \
    --channelId 'f0G6OrPH' \
    --namespace $AB_NAMESPACE \
    --userId '6ZsjpPgH' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 37 'AdminUpdateChannel' test.out

#- 38 AdminDeleteChannel
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteChannel \
    --channelId 'KISHtB8t' \
    --namespace $AB_NAMESPACE \
    --userId 'WdJM9Qc5' \
    > test.out 2>&1
eval_tap $? 38 'AdminDeleteChannel' test.out

#- 39 AdminUpdateContentS3
# body param: body
echo '{"contentType": "HmR0vknX", "customAttributes": {"O45AUtNX": {}, "STItt35O": {}, "JTfJBZX6": {}}, "fileExtension": "2yI9g5RD", "name": "rlzPFQmN", "payload": "u3ERxV0U", "preview": "TaiSzfi0", "previewMetadata": {"previewContentType": "FnBERe8q", "previewFileExtension": "NYRTYSaZ"}, "subType": "w4NqSNyl", "tags": ["cljuNM3e", "UUSD1pZG", "MfPdGIOA"], "type": "Z86un0L9", "updateContentFile": false}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminUpdateContentS3 \
    --channelId 'WUoXvfU4' \
    --contentId 'qMIpfgxw' \
    --namespace $AB_NAMESPACE \
    --userId '2ff5twRY' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 39 'AdminUpdateContentS3' test.out

#- 40 AdminUpdateContentDirect
eval_tap 0 40 'AdminUpdateContentDirect # SKIP deprecated' test.out

#- 41 AdminDeleteContent
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteContent \
    --channelId 'btdK2r4w' \
    --contentId 'Ws6IpYBx' \
    --namespace $AB_NAMESPACE \
    --userId 'afo9b4xJ' \
    > test.out 2>&1
eval_tap $? 41 'AdminDeleteContent' test.out

#- 42 AdminGetContent
$CLI_EXE \
    --sn ugc \
    --op AdminGetContent \
    --namespace $AB_NAMESPACE \
    --userId 'yNnvHKrm' \
    --limit '32' \
    --offset '96' \
    > test.out 2>&1
eval_tap $? 42 'AdminGetContent' test.out

#- 43 AdminDeleteAllUserContents
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteAllUserContents \
    --namespace $AB_NAMESPACE \
    --userId 'MmOQJrpE' \
    > test.out 2>&1
eval_tap $? 43 'AdminDeleteAllUserContents' test.out

#- 44 AdminHideUserContent
# body param: body
echo '{"isHidden": true}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminHideUserContent \
    --contentId 'yO0vyD6J' \
    --namespace $AB_NAMESPACE \
    --userId '5brVo20e' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 44 'AdminHideUserContent' test.out

#- 45 AdminGetAllGroups
$CLI_EXE \
    --sn ugc \
    --op AdminGetAllGroups \
    --namespace $AB_NAMESPACE \
    --userId '6POTjrin' \
    --limit '55' \
    --offset '72' \
    > test.out 2>&1
eval_tap $? 45 'AdminGetAllGroups' test.out

#- 46 AdminDeleteAllUserGroup
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteAllUserGroup \
    --namespace $AB_NAMESPACE \
    --userId 'VVovpAAX' \
    > test.out 2>&1
eval_tap $? 46 'AdminDeleteAllUserGroup' test.out

#- 47 AdminGetGroup
$CLI_EXE \
    --sn ugc \
    --op AdminGetGroup \
    --groupId 'NzcpbmX3' \
    --namespace $AB_NAMESPACE \
    --userId 'lLFeXCia' \
    > test.out 2>&1
eval_tap $? 47 'AdminGetGroup' test.out

#- 48 AdminUpdateGroup
# body param: body
echo '{"contents": ["XP8jBjK8", "1t2V9TVa", "uFcGkPgQ"], "name": "0hb2tLrs"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op AdminUpdateGroup \
    --groupId 'MeoZiRYk' \
    --namespace $AB_NAMESPACE \
    --userId 'bhEM1zTN' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 48 'AdminUpdateGroup' test.out

#- 49 AdminDeleteGroup
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteGroup \
    --groupId 'Y3lpincu' \
    --namespace $AB_NAMESPACE \
    --userId 'f5d5saQv' \
    > test.out 2>&1
eval_tap $? 49 'AdminDeleteGroup' test.out

#- 50 AdminGetGroupContents
$CLI_EXE \
    --sn ugc \
    --op AdminGetGroupContents \
    --groupId 'KfFRqBam' \
    --namespace $AB_NAMESPACE \
    --userId '8jPtKHTm' \
    --limit '53' \
    --offset '63' \
    > test.out 2>&1
eval_tap $? 50 'AdminGetGroupContents' test.out

#- 51 AdminDeleteAllUserStates
$CLI_EXE \
    --sn ugc \
    --op AdminDeleteAllUserStates \
    --namespace $AB_NAMESPACE \
    --userId 'o0JmcQmn' \
    > test.out 2>&1
eval_tap $? 51 'AdminDeleteAllUserStates' test.out

#- 52 SearchChannelSpecificContent
$CLI_EXE \
    --sn ugc \
    --op SearchChannelSpecificContent \
    --channelId 'sUigVynj' \
    --namespace $AB_NAMESPACE \
    --creator 'GFyVicGQ' \
    --isofficial 'AVv32ftR' \
    --limit '53' \
    --name 'fBvo6Llc' \
    --offset '1' \
    --orderby '8j1AJ3hN' \
    --sortby 'WWhADRqJ' \
    --subtype 'vaZrf2qX' \
    --tags '["QFCzRV1p", "aELj5dw3", "LK0gPYhP"]' \
    --type 'PG5sAIfY' \
    --userId 'tYozA2On' \
    > test.out 2>&1
eval_tap $? 52 'SearchChannelSpecificContent' test.out

#- 53 PublicSearchContent
$CLI_EXE \
    --sn ugc \
    --op PublicSearchContent \
    --namespace $AB_NAMESPACE \
    --creator 'tGCwQSHH' \
    --isofficial 'dPLwjTng' \
    --limit '36' \
    --name 'oYwS8oLy' \
    --offset '62' \
    --orderby 'cBBhRAYj' \
    --sortby 'R7c4x5bI' \
    --subtype 'k8pVpxdU' \
    --tags '["WOPel3Ti", "wTycqpVd", "INXzvkSp"]' \
    --type '0WbvxQWI' \
    --userId '0QGCOx7e' \
    > test.out 2>&1
eval_tap $? 53 'PublicSearchContent' test.out

#- 54 PublicGetContentBulk
# body param: body
echo '{"contentIds": ["ICkauWbF", "rSnU7d1B", "uhdwliTS"]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op PublicGetContentBulk \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 54 'PublicGetContentBulk' test.out

#- 55 GetFollowedContent
$CLI_EXE \
    --sn ugc \
    --op GetFollowedContent \
    --namespace $AB_NAMESPACE \
    --limit '61' \
    --offset '45' \
    > test.out 2>&1
eval_tap $? 55 'GetFollowedContent' test.out

#- 56 GetLikedContent
$CLI_EXE \
    --sn ugc \
    --op GetLikedContent \
    --namespace $AB_NAMESPACE \
    --isofficial 'false' \
    --limit '25' \
    --name 'U1TxiS06' \
    --offset '95' \
    --orderby 'mrVQaUr3' \
    --sortby 'oT88Dfc7' \
    --subtype '114QFGwT' \
    --tags '["zBVDg5v7", "1kGCEt7h", "1mVwIQCJ"]' \
    --type 'mQkvWbQr' \
    > test.out 2>&1
eval_tap $? 56 'GetLikedContent' test.out

#- 57 PublicDownloadContentByShareCode
$CLI_EXE \
    --sn ugc \
    --op PublicDownloadContentByShareCode \
    --namespace $AB_NAMESPACE \
    --shareCode 'n2W0VkOF' \
    > test.out 2>&1
eval_tap $? 57 'PublicDownloadContentByShareCode' test.out

#- 58 PublicDownloadContentByContentID
$CLI_EXE \
    --sn ugc \
    --op PublicDownloadContentByContentID \
    --contentId '0pQOY0UC' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 58 'PublicDownloadContentByContentID' test.out

#- 59 AddDownloadCount
$CLI_EXE \
    --sn ugc \
    --op AddDownloadCount \
    --contentId 'cViiFKNj' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 59 'AddDownloadCount' test.out

#- 60 UpdateContentLikeStatus
# body param: body
echo '{"likeStatus": false}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op UpdateContentLikeStatus \
    --contentId 'VT66sHYP' \
    --namespace $AB_NAMESPACE \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 60 'UpdateContentLikeStatus' test.out

#- 61 PublicDownloadContentPreview
$CLI_EXE \
    --sn ugc \
    --op PublicDownloadContentPreview \
    --contentId 'gVsfhoEi' \
    --namespace $AB_NAMESPACE \
    > test.out 2>&1
eval_tap $? 61 'PublicDownloadContentPreview' test.out

#- 62 GetTag
$CLI_EXE \
    --sn ugc \
    --op GetTag \
    --namespace $AB_NAMESPACE \
    --limit '6' \
    --offset '76' \
    > test.out 2>&1
eval_tap $? 62 'GetTag' test.out

#- 63 GetType
$CLI_EXE \
    --sn ugc \
    --op GetType \
    --namespace $AB_NAMESPACE \
    --limit '74' \
    --offset '9' \
    > test.out 2>&1
eval_tap $? 63 'GetType' test.out

#- 64 PublicSearchCreator
$CLI_EXE \
    --sn ugc \
    --op PublicSearchCreator \
    --namespace $AB_NAMESPACE \
    --limit '47' \
    --offset '53' \
    --orderby '4IP0NVna' \
    --sortby 'angorhVF' \
    > test.out 2>&1
eval_tap $? 64 'PublicSearchCreator' test.out

#- 65 GetFollowedUsers
$CLI_EXE \
    --sn ugc \
    --op GetFollowedUsers \
    --namespace $AB_NAMESPACE \
    --limit '32' \
    --offset '86' \
    > test.out 2>&1
eval_tap $? 65 'GetFollowedUsers' test.out

#- 66 PublicGetCreator
$CLI_EXE \
    --sn ugc \
    --op PublicGetCreator \
    --namespace $AB_NAMESPACE \
    --userId 'TRuQyMro' \
    > test.out 2>&1
eval_tap $? 66 'PublicGetCreator' test.out

#- 67 GetChannels
$CLI_EXE \
    --sn ugc \
    --op GetChannels \
    --namespace $AB_NAMESPACE \
    --userId 'T2hNfKJ7' \
    --limit '33' \
    --offset '10' \
    > test.out 2>&1
eval_tap $? 67 'GetChannels' test.out

#- 68 CreateChannel
# body param: body
echo '{"name": "8sifSPmY"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op CreateChannel \
    --namespace $AB_NAMESPACE \
    --userId 'SsBxtyKW' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 68 'CreateChannel' test.out

#- 69 DeleteAllUserChannel
$CLI_EXE \
    --sn ugc \
    --op DeleteAllUserChannel \
    --namespace $AB_NAMESPACE \
    --userId 'ssEn5VEv' \
    > test.out 2>&1
eval_tap $? 69 'DeleteAllUserChannel' test.out

#- 70 UpdateChannel
# body param: body
echo '{"name": "IMEB4pl5"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op UpdateChannel \
    --channelId '06fLCG6E' \
    --namespace $AB_NAMESPACE \
    --userId 'Al7d3Ks6' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 70 'UpdateChannel' test.out

#- 71 DeleteChannel
$CLI_EXE \
    --sn ugc \
    --op DeleteChannel \
    --channelId '5thtnjcM' \
    --namespace $AB_NAMESPACE \
    --userId 'Sw1J42ft' \
    > test.out 2>&1
eval_tap $? 71 'DeleteChannel' test.out

#- 72 CreateContentDirect
eval_tap 0 72 'CreateContentDirect # SKIP deprecated' test.out

#- 73 CreateContentS3
# body param: body
echo '{"contentType": "hKUobas2", "customAttributes": {"CAlSxxVh": {}, "DR9hlazn": {}, "etBUGcQz": {}}, "fileExtension": "2Wvdiclk", "name": "YGDL2ckC", "preview": "9cdzaLna", "previewMetadata": {"previewContentType": "jQ8GnJpA", "previewFileExtension": "Liddv9UU"}, "subType": "tG1tEECs", "tags": ["m8xaDOz0", "tMlpFuJV", "Xo9s0JPG"], "type": "8cgjHQo9"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op CreateContentS3 \
    --channelId 'HoLLyUnP' \
    --namespace $AB_NAMESPACE \
    --userId 'TiCD0038' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 73 'CreateContentS3' test.out

#- 74 UpdateContentS3
# body param: body
echo '{"contentType": "or8wR0tu", "customAttributes": {"wIJnrSI2": {}, "IFcRwSoM": {}, "TuJziuDN": {}}, "fileExtension": "bOydiu3l", "name": "OaruuYw0", "payload": "iUuts6bC", "preview": "hMK1gcx8", "previewMetadata": {"previewContentType": "p9fyv5Po", "previewFileExtension": "MJeTIQix"}, "subType": "1FEvzlip", "tags": ["E7r0vhh2", "1v5772Ao", "pmjI7CbY"], "type": "2WuwRUT9", "updateContentFile": true}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op UpdateContentS3 \
    --channelId 'ivgC4mJ5' \
    --contentId 'OHuNEVQK' \
    --namespace $AB_NAMESPACE \
    --userId '4Mvk00I9' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 74 'UpdateContentS3' test.out

#- 75 UpdateContentDirect
eval_tap 0 75 'UpdateContentDirect # SKIP deprecated' test.out

#- 76 DeleteContent
$CLI_EXE \
    --sn ugc \
    --op DeleteContent \
    --channelId 'GqAhhjNI' \
    --contentId 'ivdIcaEQ' \
    --namespace $AB_NAMESPACE \
    --userId 'fNETQCBP' \
    > test.out 2>&1
eval_tap $? 76 'DeleteContent' test.out

#- 77 PublicGetUserContent
$CLI_EXE \
    --sn ugc \
    --op PublicGetUserContent \
    --namespace $AB_NAMESPACE \
    --userId 'K1mYwKVQ' \
    --limit '29' \
    --offset '92' \
    > test.out 2>&1
eval_tap $? 77 'PublicGetUserContent' test.out

#- 78 DeleteAllUserContents
$CLI_EXE \
    --sn ugc \
    --op DeleteAllUserContents \
    --namespace $AB_NAMESPACE \
    --userId 'ydbYjXZy' \
    > test.out 2>&1
eval_tap $? 78 'DeleteAllUserContents' test.out

#- 79 UpdateScreenshots
# body param: body
echo '{"screenshots": [{"description": "BpqhCJBt", "screenshotId": "FOm3iCpu"}, {"description": "0lhhgutt", "screenshotId": "3rQuKP1O"}, {"description": "EtKFBjNi", "screenshotId": "hHU8GP8T"}]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op UpdateScreenshots \
    --contentId 'RVypSvYX' \
    --namespace $AB_NAMESPACE \
    --userId 'Kz4BGjbs' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 79 'UpdateScreenshots' test.out

#- 80 UploadContentScreenshot
# body param: body
echo '{"screenshots": [{"contentType": "rRBV8azt", "description": "J86yQK1A", "fileExtension": "jpeg"}, {"contentType": "hOhenJi6", "description": "dNVF7zwj", "fileExtension": "png"}, {"contentType": "qlcD2Lza", "description": "OwIF5tEs", "fileExtension": "jpg"}]}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op UploadContentScreenshot \
    --contentId 'PcPSL2xm' \
    --namespace $AB_NAMESPACE \
    --userId 'jViKkKw4' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 80 'UploadContentScreenshot' test.out

#- 81 DeleteContentScreenshot
$CLI_EXE \
    --sn ugc \
    --op DeleteContentScreenshot \
    --contentId 'gHA4CaLs' \
    --namespace $AB_NAMESPACE \
    --screenshotId 'PqRsTdKz' \
    --userId 'cKtkGcvn' \
    > test.out 2>&1
eval_tap $? 81 'DeleteContentScreenshot' test.out

#- 82 UpdateUserFollowStatus
# body param: body
echo '{"followStatus": false}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op UpdateUserFollowStatus \
    --namespace $AB_NAMESPACE \
    --userId 'Wse6VLPk' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 82 'UpdateUserFollowStatus' test.out

#- 83 GetPublicFollowers
$CLI_EXE \
    --sn ugc \
    --op GetPublicFollowers \
    --namespace $AB_NAMESPACE \
    --userId 'M1VTrQBy' \
    --limit '46' \
    --offset '26' \
    > test.out 2>&1
eval_tap $? 83 'GetPublicFollowers' test.out

#- 84 GetPublicFollowing
$CLI_EXE \
    --sn ugc \
    --op GetPublicFollowing \
    --namespace $AB_NAMESPACE \
    --userId 'hJ7lbBLw' \
    --limit '47' \
    --offset '6' \
    > test.out 2>&1
eval_tap $? 84 'GetPublicFollowing' test.out

#- 85 GetGroups
$CLI_EXE \
    --sn ugc \
    --op GetGroups \
    --namespace $AB_NAMESPACE \
    --userId 'y1WQM5qU' \
    --limit '91' \
    --offset '41' \
    > test.out 2>&1
eval_tap $? 85 'GetGroups' test.out

#- 86 CreateGroup
# body param: body
echo '{"contents": ["8baUqkzS", "r41y6RPB", "HJuPjj8z"], "name": "DwOk0Igm"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op CreateGroup \
    --namespace $AB_NAMESPACE \
    --userId 'YfUTpFzy' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 86 'CreateGroup' test.out

#- 87 DeleteAllUserGroup
$CLI_EXE \
    --sn ugc \
    --op DeleteAllUserGroup \
    --namespace $AB_NAMESPACE \
    --userId 'QhPVhRGX' \
    > test.out 2>&1
eval_tap $? 87 'DeleteAllUserGroup' test.out

#- 88 GetGroup
$CLI_EXE \
    --sn ugc \
    --op GetGroup \
    --groupId '9xlUKhXI' \
    --namespace $AB_NAMESPACE \
    --userId '8mL8OIhv' \
    > test.out 2>&1
eval_tap $? 88 'GetGroup' test.out

#- 89 UpdateGroup
# body param: body
echo '{"contents": ["P68xE68d", "zohxhbej", "2caIIfkX"], "name": "DY7jnhp3"}' > $TEMP_JSON_INPUT
$CLI_EXE \
    --sn ugc \
    --op UpdateGroup \
    --groupId 'qY6T7TUE' \
    --namespace $AB_NAMESPACE \
    --userId 'BotSNIwG' \
    --reqfile $TEMP_JSON_INPUT \
    > test.out 2>&1
eval_tap $? 89 'UpdateGroup' test.out

#- 90 DeleteGroup
$CLI_EXE \
    --sn ugc \
    --op DeleteGroup \
    --groupId 'hia6cqoW' \
    --namespace $AB_NAMESPACE \
    --userId 'mnhtuzxi' \
    > test.out 2>&1
eval_tap $? 90 'DeleteGroup' test.out

#- 91 GetGroupContent
$CLI_EXE \
    --sn ugc \
    --op GetGroupContent \
    --groupId 'r12r0VUW' \
    --namespace $AB_NAMESPACE \
    --userId 'I0kJAczj' \
    --limit '50' \
    --offset '55' \
    > test.out 2>&1
eval_tap $? 91 'GetGroupContent' test.out

#- 92 DeleteAllUserStates
$CLI_EXE \
    --sn ugc \
    --op DeleteAllUserStates \
    --namespace $AB_NAMESPACE \
    --userId 'wU6uisej' \
    > test.out 2>&1
eval_tap $? 92 'DeleteAllUserStates' test.out


# remove artifacts
rm -f "$CLI_TOKEN_FILE"
rm -f "$TEMP_JSON_INPUT"
rm -f "$TEMP_FILE_UPLOAD"

exit $EXIT_CODE