// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System.Net;
using System.IO;
using System.Text.Json;
using AccelByte.Sdk.Api.Platform.Model;
using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Util;

namespace AccelByte.Sdk.Api.Platform.Operation
{
    /// <summary>
    /// getUserEntitlementBySku
    ///
    /// Get user entitlement by sku.
    /// 
    /// Other detail info:
    /// 
    ///   * Required permission : resource="ADMIN:NAMESPACE:{namespace}:USER:{userId}:ENTITLEMENT", action=2 (READ)
    /// </summary>
    public class GetUserEntitlementBySku : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static GetUserEntitlementBySkuBuilder Builder { get => new GetUserEntitlementBySkuBuilder(); }

        public class GetUserEntitlementBySkuBuilder
            : OperationBuilder<GetUserEntitlementBySkuBuilder>
        {

            public bool? ActiveOnly { get; set; }

            public GetUserEntitlementBySkuEntitlementClazz? EntitlementClazz { get; set; }





            internal GetUserEntitlementBySkuBuilder() { }


            public GetUserEntitlementBySkuBuilder SetActiveOnly(bool _activeOnly)
            {
                ActiveOnly = _activeOnly;
                return this;
            }

            public GetUserEntitlementBySkuBuilder SetEntitlementClazz(GetUserEntitlementBySkuEntitlementClazz _entitlementClazz)
            {
                EntitlementClazz = _entitlementClazz;
                return this;
            }





            public GetUserEntitlementBySku Build(
                string namespace_,
                string userId,
                string sku
            )
            {
                GetUserEntitlementBySku op = new GetUserEntitlementBySku(this,
                    namespace_,                    
                    userId,                    
                    sku                    
                );
                op.PreferredSecurityMethod = PreferredSecurityMethod;

                return op;
            }
        }

        private GetUserEntitlementBySku(GetUserEntitlementBySkuBuilder builder,
            string namespace_,
            string userId,
            string sku
        )
        {
            PathParams["namespace"] = namespace_;
            PathParams["userId"] = userId;
            
            if (builder.ActiveOnly != null) QueryParams["activeOnly"] = Convert.ToString(builder.ActiveOnly)!;
            if (builder.EntitlementClazz is not null) QueryParams["entitlementClazz"] = builder.EntitlementClazz.Value;
            if (sku is not null) QueryParams["sku"] = sku;
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        public GetUserEntitlementBySku(
            string namespace_,            
            string userId,            
            bool? activeOnly,            
            GetUserEntitlementBySkuEntitlementClazz? entitlementClazz,            
            string sku            
        )
        {
            PathParams["namespace"] = namespace_;
            PathParams["userId"] = userId;
            
            if (activeOnly != null) QueryParams["activeOnly"] = Convert.ToString(activeOnly)!;
            if (entitlementClazz is not null) QueryParams["entitlementClazz"] = entitlementClazz.Value;
            if (sku is not null) QueryParams["sku"] = sku;
            

            
            
            

            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/platform/admin/namespaces/{namespace}/users/{userId}/entitlements/bySku";

        public override HttpMethod Method => HttpMethod.Get;

        public override string[] Consumes => new string[] {  };

        public override string[] Produces => new string[] { "application/json" };

        [Obsolete("Use 'Securities' property instead.")]
        public override string? Security { get; set; } = "Bearer";
        
        public Model.EntitlementInfo? ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {            
            if (code == (HttpStatusCode)204)
            {
                return null;
            }
            else if (code == (HttpStatusCode)201)
            {
                return JsonSerializer.Deserialize<Model.EntitlementInfo>(payload);
            }
            else if (code == (HttpStatusCode)200)
            {
                return JsonSerializer.Deserialize<Model.EntitlementInfo>(payload);
            }
            
            var payloadString = Helper.ConvertInputStreamToString(payload);
            
            throw new HttpResponseException(code, payloadString);
        }
    }

    public class GetUserEntitlementBySkuEntitlementClazz : StringEnum<GetUserEntitlementBySkuEntitlementClazz>
    {
        public static readonly GetUserEntitlementBySkuEntitlementClazz APP
            = new GetUserEntitlementBySkuEntitlementClazz("APP");

        public static readonly GetUserEntitlementBySkuEntitlementClazz CODE
            = new GetUserEntitlementBySkuEntitlementClazz("CODE");

        public static readonly GetUserEntitlementBySkuEntitlementClazz ENTITLEMENT
            = new GetUserEntitlementBySkuEntitlementClazz("ENTITLEMENT");

        public static readonly GetUserEntitlementBySkuEntitlementClazz LOOTBOX
            = new GetUserEntitlementBySkuEntitlementClazz("LOOTBOX");

        public static readonly GetUserEntitlementBySkuEntitlementClazz MEDIA
            = new GetUserEntitlementBySkuEntitlementClazz("MEDIA");

        public static readonly GetUserEntitlementBySkuEntitlementClazz OPTIONBOX
            = new GetUserEntitlementBySkuEntitlementClazz("OPTIONBOX");

        public static readonly GetUserEntitlementBySkuEntitlementClazz SUBSCRIPTION
            = new GetUserEntitlementBySkuEntitlementClazz("SUBSCRIPTION");


        public static implicit operator GetUserEntitlementBySkuEntitlementClazz(string value)
        {
            return NewValue(value);
        }

        public GetUserEntitlementBySkuEntitlementClazz(string enumValue)
            : base(enumValue)
        {

        }
    }

}