// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System.Net;
using System.IO;
using System.Text.Json;
using AccelByte.Sdk.Api.Leaderboard.Model;
using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Util;

namespace AccelByte.Sdk.Api.Leaderboard.Operation
{
    /// <summary>
    /// deleteUserRankingByLeaderboardCodeAdminV3
    ///
    /// 
    /// 
    ///  [Test Facility Only]
    /// 
    /// 
    /// 
    /// 
    /// Required permission 'ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]'
    /// 
    /// 
    /// 
    /// 
    /// This endpoint will delete user ranking by leaderboard code
    /// 
    /// 
    /// 
    /// 
    /// Note: this endpoint only works on development environment.
    /// </summary>
    public class DeleteUserRankingByLeaderboardCodeAdminV3 : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static DeleteUserRankingByLeaderboardCodeAdminV3Builder Builder { get => new DeleteUserRankingByLeaderboardCodeAdminV3Builder(); }

        public class DeleteUserRankingByLeaderboardCodeAdminV3Builder
            : OperationBuilder<DeleteUserRankingByLeaderboardCodeAdminV3Builder>
        {





            internal DeleteUserRankingByLeaderboardCodeAdminV3Builder() { }






            public DeleteUserRankingByLeaderboardCodeAdminV3 Build(
                string leaderboardCode,
                string namespace_
            )
            {
                DeleteUserRankingByLeaderboardCodeAdminV3 op = new DeleteUserRankingByLeaderboardCodeAdminV3(this,
                    leaderboardCode,
                    namespace_
                );
                op.PreferredSecurityMethod = PreferredSecurityMethod;

                return op;
            }
        }

        private DeleteUserRankingByLeaderboardCodeAdminV3(DeleteUserRankingByLeaderboardCodeAdminV3Builder builder,
            string leaderboardCode,
            string namespace_
        )
        {
            PathParams["leaderboardCode"] = leaderboardCode;
            PathParams["namespace"] = namespace_;







            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        public DeleteUserRankingByLeaderboardCodeAdminV3(
            string leaderboardCode,
            string namespace_
        )
        {
            PathParams["leaderboardCode"] = leaderboardCode;
            PathParams["namespace"] = namespace_;







            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/reset";

        public override HttpMethod Method => HttpMethod.Delete;

        public override string[] Consumes => new string[] { };

        public override string[] Produces => new string[] { "application/json" };

        [Obsolete("2022-04-19 - Use 'Securities' property instead.")]
        public override string? Security { get; set; } = "Bearer";

        public void ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            if (code == (HttpStatusCode)204)
            {
                return;
            }

            var payloadString = Helper.ConvertInputStreamToString(payload);

            throw new HttpResponseException(code, payloadString);
        }
    }

}