// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using AccelByte.Sdk.Api.Iam.Model;
using AccelByte.Sdk.Api.Iam.Operation.Deprecated;
using AccelByte.Sdk.Api.Iam.Wrapper;
using AccelByte.Sdk.Core;

namespace AccelByte.Sdk.Api
{
    public static class IamRolesDeprecated_OpExts
    {
        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static List<Iam.Model.ModelRoleResponseWithManagers>? Execute(
            this GetRoles.GetRolesBuilder builder
        )
        {
            GetRoles op = builder.Build(
            );

            return ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).GetRoles(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static Iam.Model.AccountcommonRole? Execute(
            this CreateRole.CreateRoleBuilder builder,
            ModelRoleCreateRequest body
        )
        {
            CreateRole op = builder.Build(
                body
            );

            return ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).CreateRole(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static Iam.Model.ModelRoleResponse? Execute(
            this GetRole.GetRoleBuilder builder,
            string roleId
        )
        {
            GetRole op = builder.Build(
                roleId
            );

            return ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).GetRole(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static Iam.Model.ModelRoleResponse? Execute(
            this UpdateRole.UpdateRoleBuilder builder,
            ModelRoleUpdateRequest body,
            string roleId
        )
        {
            UpdateRole op = builder.Build(
                body,
                roleId
            );

            return ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).UpdateRole(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this DeleteRole.DeleteRoleBuilder builder,
            string roleId
        )
        {
            DeleteRole op = builder.Build(
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).DeleteRole(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static Iam.Model.ModelRoleAdminStatusResponse? Execute(
            this GetRoleAdminStatus.GetRoleAdminStatusBuilder builder,
            string roleId
        )
        {
            GetRoleAdminStatus op = builder.Build(
                roleId
            );

            return ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).GetRoleAdminStatus(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this SetRoleAsAdmin.SetRoleAsAdminBuilder builder,
            string roleId
        )
        {
            SetRoleAsAdmin op = builder.Build(
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).SetRoleAsAdmin(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this RemoveRoleAdmin.RemoveRoleAdminBuilder builder,
            string roleId
        )
        {
            RemoveRoleAdmin op = builder.Build(
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).RemoveRoleAdmin(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static Iam.Model.ModelRoleManagersResponse? Execute(
            this GetRoleManagers.GetRoleManagersBuilder builder,
            string roleId
        )
        {
            GetRoleManagers op = builder.Build(
                roleId
            );

            return ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).GetRoleManagers(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this AddRoleManagers.AddRoleManagersBuilder builder,
            ModelRoleManagersRequest body,
            string roleId
        )
        {
            AddRoleManagers op = builder.Build(
                body,
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).AddRoleManagers(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this RemoveRoleManagers.RemoveRoleManagersBuilder builder,
            ModelRoleManagersRequest body,
            string roleId
        )
        {
            RemoveRoleManagers op = builder.Build(
                body,
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).RemoveRoleManagers(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static Iam.Model.ModelRoleMembersResponse? Execute(
            this GetRoleMembers.GetRoleMembersBuilder builder,
            string roleId
        )
        {
            GetRoleMembers op = builder.Build(
                roleId
            );

            return ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).GetRoleMembers(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this AddRoleMembers.AddRoleMembersBuilder builder,
            ModelRoleMembersRequest body,
            string roleId
        )
        {
            AddRoleMembers op = builder.Build(
                body,
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).AddRoleMembers(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this RemoveRoleMembers.RemoveRoleMembersBuilder builder,
            ModelRoleMembersRequest body,
            string roleId
        )
        {
            RemoveRoleMembers op = builder.Build(
                body,
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).RemoveRoleMembers(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this UpdateRolePermissions.UpdateRolePermissionsBuilder builder,
            AccountcommonPermissions body,
            string roleId
        )
        {
            UpdateRolePermissions op = builder.Build(
                body,
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).UpdateRolePermissions(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this AddRolePermission.AddRolePermissionBuilder builder,
            ModelUpdatePermissionScheduleRequest body,
            long action,
            string resource,
            string roleId
        )
        {
            AddRolePermission op = builder.Build(
                body,
                action,
                resource,
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).AddRolePermission(op);
        }

        [Obsolete(DiagnosticId ="ab_deprecated_operation_wrapper")]
        public static void Execute(
            this DeleteRolePermission.DeleteRolePermissionBuilder builder,
            long action,
            string resource,
            string roleId
        )
        {
            DeleteRolePermission op = builder.Build(
                action,
                resource,
                roleId
            );

            ((Iam.Wrapper.RolesDeprecated)builder.WrapperObject!).DeleteRolePermission(op);
        }

    }
}