// Copyright (c) 2022-2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
using AccelByte.Sdk.Api.Eventlog.Model;
using AccelByte.Sdk.Api.Eventlog.Operation;
using AccelByte.Sdk.Api.Eventlog.Wrapper;
using AccelByte.Sdk.Core;

namespace AccelByte.Sdk.Api
{
    public static class EventlogEventDescriptions_OpExts
    {
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleAgentType? Execute(
            this AgentTypeDescriptionHandler.AgentTypeDescriptionHandlerBuilder builder
        )
        {
            AgentTypeDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).AgentTypeDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleAgentType?> ExecuteAsync(
            this AgentTypeDescriptionHandler.AgentTypeDescriptionHandlerBuilder builder
        )
        {
            AgentTypeDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).AgentTypeDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleAgentType? Execute(
            this SpecificAgentTypeDescriptionHandler.SpecificAgentTypeDescriptionHandlerBuilder builder
        )
        {
            SpecificAgentTypeDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificAgentTypeDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleAgentType?> ExecuteAsync(
            this SpecificAgentTypeDescriptionHandler.SpecificAgentTypeDescriptionHandlerBuilder builder
        )
        {
            SpecificAgentTypeDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificAgentTypeDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleEventID? Execute(
            this EventIDDescriptionHandler.EventIDDescriptionHandlerBuilder builder
        )
        {
            EventIDDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).EventIDDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleEventID?> ExecuteAsync(
            this EventIDDescriptionHandler.EventIDDescriptionHandlerBuilder builder
        )
        {
            EventIDDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).EventIDDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleEventID? Execute(
            this SpecificEventIDDescriptionHandler.SpecificEventIDDescriptionHandlerBuilder builder
        )
        {
            SpecificEventIDDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificEventIDDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleEventID?> ExecuteAsync(
            this SpecificEventIDDescriptionHandler.SpecificEventIDDescriptionHandlerBuilder builder
        )
        {
            SpecificEventIDDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificEventIDDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleEventLevel? Execute(
            this EventLevelDescriptionHandler.EventLevelDescriptionHandlerBuilder builder
        )
        {
            EventLevelDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).EventLevelDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleEventLevel?> ExecuteAsync(
            this EventLevelDescriptionHandler.EventLevelDescriptionHandlerBuilder builder
        )
        {
            EventLevelDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).EventLevelDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleEventLevel? Execute(
            this SpecificEventLevelDescriptionHandler.SpecificEventLevelDescriptionHandlerBuilder builder
        )
        {
            SpecificEventLevelDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificEventLevelDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleEventLevel?> ExecuteAsync(
            this SpecificEventLevelDescriptionHandler.SpecificEventLevelDescriptionHandlerBuilder builder
        )
        {
            SpecificEventLevelDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificEventLevelDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleEventType? Execute(
            this EventTypeDescriptionHandler.EventTypeDescriptionHandlerBuilder builder
        )
        {
            EventTypeDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).EventTypeDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleEventType?> ExecuteAsync(
            this EventTypeDescriptionHandler.EventTypeDescriptionHandlerBuilder builder
        )
        {
            EventTypeDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).EventTypeDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleEventType? Execute(
            this SpecificEventTypeDescriptionHandler.SpecificEventTypeDescriptionHandlerBuilder builder
        )
        {
            SpecificEventTypeDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificEventTypeDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleEventType?> ExecuteAsync(
            this SpecificEventTypeDescriptionHandler.SpecificEventTypeDescriptionHandlerBuilder builder
        )
        {
            SpecificEventTypeDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificEventTypeDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleUX? Execute(
            this UXNameDescriptionHandler.UXNameDescriptionHandlerBuilder builder
        )
        {
            UXNameDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).UXNameDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleUX?> ExecuteAsync(
            this UXNameDescriptionHandler.UXNameDescriptionHandlerBuilder builder
        )
        {
            UXNameDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).UXNameDescriptionHandlerAsync(op);
        }
        [Obsolete(DiagnosticId = "ab_deprecated_operation_wrapper")]
        public static Eventlog.Model.ModelsMultipleUX? Execute(
            this SpecificUXDescriptionHandler.SpecificUXDescriptionHandlerBuilder builder
        )
        {
            SpecificUXDescriptionHandler op = builder.Build(
            );

            return ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificUXDescriptionHandler(op);
        }
        public static async Task<Eventlog.Model.ModelsMultipleUX?> ExecuteAsync(
            this SpecificUXDescriptionHandler.SpecificUXDescriptionHandlerBuilder builder
        )
        {
            SpecificUXDescriptionHandler op = builder.Build(
            );

            return await ((Eventlog.Wrapper.EventDescriptions)builder.WrapperObject!).SpecificUXDescriptionHandlerAsync(op);
        }
    }
}