// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System.Net;
using System.IO;
using System.Text.Json;
using AccelByte.Sdk.Api.Iam.Model;
using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Util;

namespace AccelByte.Sdk.Api.Iam.Operation
{
    /// <summary>
    /// AdminUpdateClientV3
    ///
    /// Updates an OAuth 2.0 client. Specify only the fields you want to update in the request payload.
    /// 
    /// **Note for Multi Tenant Mode (Confidential Client):**
    /// Super admin can set any valid format permission with resource & action.
    /// Studio admin & game admin can only set permission with these 2 ways:
    /// * Permission module, available from _GET /iam/v3/admin/clientConfig/permissions_
    /// * Fixed prefix custom permissions, the allowed prefix are:
    /// 1. ***CUSTOM:ADMIN:NAMESPACE:{namespace}***
    /// 2. ***CUSTOM:NAMESPACE:{namespace}***
    /// </summary>
    public class AdminUpdateClientV3 : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static AdminUpdateClientV3Builder Builder { get => new AdminUpdateClientV3Builder(); }

        public class AdminUpdateClientV3Builder
            : OperationBuilder<AdminUpdateClientV3Builder>
        {





            internal AdminUpdateClientV3Builder() { }






            public AdminUpdateClientV3 Build(
                ClientmodelClientUpdateV3Request body,
                string clientId,
                string namespace_
            )
            {
                AdminUpdateClientV3 op = new AdminUpdateClientV3(this,
                    body,
                    clientId,
                    namespace_
                );
                op.PreferredSecurityMethod = PreferredSecurityMethod;
                op.RequestJsonOptions = RequestJsonOptions;
                op.ResponseJsonOptions = ResponseJsonOptions;
                op.FlightId = FlightId;

                return op;
            }
        }

        private AdminUpdateClientV3(AdminUpdateClientV3Builder builder,
            ClientmodelClientUpdateV3Request body,
            string clientId,
            string namespace_
        )
        {
            PathParams["clientId"] = clientId;
            PathParams["namespace"] = namespace_;





            BodyParams = body;


            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        public AdminUpdateClientV3(
            string clientId,
            string namespace_,
            Model.ClientmodelClientUpdateV3Request body
        )
        {
            PathParams["clientId"] = clientId;
            PathParams["namespace"] = namespace_;





            BodyParams = body;


            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/iam/v3/admin/namespaces/{namespace}/clients/{clientId}";

        public override HttpMethod Method => HttpMethod.Patch;

        public override string[] Consumes => new string[] { "application/json" };

        public override string[] Produces => new string[] { "application/json" };

        [Obsolete("2022-04-19 - Use 'Securities' property instead.")]
        public override string? Security { get; set; } = "Bearer";

        public Model.ClientmodelClientV3Response? ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            if (code == (HttpStatusCode)204)
            {
                return null;
            }
            else if (code == (HttpStatusCode)201)
            {
                if (ResponseJsonOptions != null)
                    return JsonSerializer.Deserialize<Model.ClientmodelClientV3Response>(payload, ResponseJsonOptions);
                else
                    return JsonSerializer.Deserialize<Model.ClientmodelClientV3Response>(payload);
            }
            else if (code == (HttpStatusCode)200)
            {
                return JsonSerializer.Deserialize<Model.ClientmodelClientV3Response>(payload, ResponseJsonOptions);
            }

            var payloadString = Helper.ConvertInputStreamToString(payload);

            throw new HttpResponseException(code, payloadString);
        }
    }

}