// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
using System.Text.Json.Serialization;
using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Converters;

namespace AccelByte.Sdk.Api.Platform.Model
{
    public class DurableEntitlementRevocationConfig : AccelByte.Sdk.Core.Model
    {
        [JsonPropertyName("enabled")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? Enabled { get; set; }

        [JsonPropertyName("strategy")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonStringEnum]
        public DurableEntitlementRevocationConfigStrategy? Strategy { get; set; }

    }



    public class DurableEntitlementRevocationConfigStrategy : StringEnum<DurableEntitlementRevocationConfigStrategy>
    {
        public static readonly DurableEntitlementRevocationConfigStrategy REVOKEORREPORT
            = new DurableEntitlementRevocationConfigStrategy("REVOKE_OR_REPORT");


        public static implicit operator DurableEntitlementRevocationConfigStrategy(string value)
        {
            return NewValue(value);
        }

        public DurableEntitlementRevocationConfigStrategy(string enumValue)
            : base(enumValue)
        {

        }
    }
}