// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
using AccelByte.Sdk.Api.Leaderboard.Model;
using AccelByte.Sdk.Api.Leaderboard.Operation;
using AccelByte.Sdk.Core;

namespace AccelByte.Sdk.Api.Leaderboard.Wrapper
{
    public class UserVisibilityV3
    {
        private readonly AccelByteSDK _sdk;

        public UserVisibilityV3(AccelByteSDK sdk)
        {
            _sdk = sdk;
        }

        #region Operation Builders
        public GetHiddenUsersV3.GetHiddenUsersV3Builder GetHiddenUsersV3Op
        {
            get { return Operation.GetHiddenUsersV3.Builder.SetWrapperObject(this); }
        }
        public GetUserVisibilityStatusV3.GetUserVisibilityStatusV3Builder GetUserVisibilityStatusV3Op
        {
            get { return Operation.GetUserVisibilityStatusV3.Builder.SetWrapperObject(this); }
        }
        public SetUserLeaderboardVisibilityV3.SetUserLeaderboardVisibilityV3Builder SetUserLeaderboardVisibilityV3Op
        {
            get { return Operation.SetUserLeaderboardVisibilityV3.Builder.SetWrapperObject(this); }
        }
        public SetUserVisibilityV3.SetUserVisibilityV3Builder SetUserVisibilityV3Op
        {
            get { return Operation.SetUserVisibilityV3.Builder.SetWrapperObject(this); }
        }
        #endregion

        public Model.ModelsGetHiddenUserResponse? GetHiddenUsersV3(GetHiddenUsersV3 input)
        {
            var response = _sdk.RunRequest(input);

            return input.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
        }
        public Model.ModelsGetUserVisibilityResponse? GetUserVisibilityStatusV3(GetUserVisibilityStatusV3 input)
        {
            var response = _sdk.RunRequest(input);

            return input.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
        }
        public Model.ModelsGetUserVisibilityResponse? SetUserLeaderboardVisibilityV3(SetUserLeaderboardVisibilityV3 input)
        {
            var response = _sdk.RunRequest(input);

            return input.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
        }
        public Model.ModelsGetUserVisibilityResponse? SetUserVisibilityV3(SetUserVisibilityV3 input)
        {
            var response = _sdk.RunRequest(input);

            return input.ParseResponse(
                    response.Code,
                    response.ContentType,
                    response.Payload);
        }
    }
}