// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System.Net;
using System.IO;
using System.Text.Json;
using AccelByte.Sdk.Api.Session.Model;
using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Util;

namespace AccelByte.Sdk.Api.Session.Operation
{
    /// <summary>
    /// publicReplaceSessionStorageUserV2
    ///
    /// 
    /// Replace entire Session Storage User with the request body. No merging is performed.
    /// 
    /// User (regular token): Can only replace own user session storage. Complete replacement.
    /// Game Admin (client token): Can replace any user's session storage. Complete replacement.
    /// 
    /// PUT semantics: The request body completely replaces the existing storage, no partial updates.
    /// Example request:
    /// {
    /// "weapon": "sword",
    /// "armor": "leather"
    /// }
    /// 
    /// Session Storage feature only available for Gamesession.
    /// </summary>
    public class PublicReplaceSessionStorageUserV2 : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static PublicReplaceSessionStorageUserV2Builder Builder { get => new PublicReplaceSessionStorageUserV2Builder(); }

        public class PublicReplaceSessionStorageUserV2Builder
            : OperationBuilder<PublicReplaceSessionStorageUserV2Builder>
        {





            internal PublicReplaceSessionStorageUserV2Builder() { }






            public PublicReplaceSessionStorageUserV2 Build(
                Dictionary<string, object> body,
                string namespace_,
                string sessionId,
                string userId
            )
            {
                PublicReplaceSessionStorageUserV2 op = new PublicReplaceSessionStorageUserV2(this,
                    body,
                    namespace_,
                    sessionId,
                    userId
                );
                op.PreferredSecurityMethod = PreferredSecurityMethod;
                op.RequestJsonOptions = RequestJsonOptions;
                op.ResponseJsonOptions = ResponseJsonOptions;
                op.FlightId = FlightId;

                return op;
            }
        }

        private PublicReplaceSessionStorageUserV2(PublicReplaceSessionStorageUserV2Builder builder,
            Dictionary<string, object> body,
            string namespace_,
            string sessionId,
            string userId
        )
        {
            PathParams["namespace"] = namespace_;
            PathParams["sessionId"] = sessionId;
            PathParams["userId"] = userId;





            BodyParams = body;


            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        public PublicReplaceSessionStorageUserV2(
            string namespace_,
            string sessionId,
            string userId,
            Dictionary<string, object> body
        )
        {
            PathParams["namespace"] = namespace_;
            PathParams["sessionId"] = sessionId;
            PathParams["userId"] = userId;





            BodyParams = body;


            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/session/v2/public/namespaces/{namespace}/sessions/{sessionId}/storage/users/{userId}";

        public override HttpMethod Method => HttpMethod.Put;

        public override string[] Consumes => new string[] { "application/json" };

        public override string[] Produces => new string[] { "application/json" };

        [Obsolete("2022-04-19 - Use 'Securities' property instead.")]
        public override string? Security { get; set; } = "Bearer";

        public Dictionary<string, object>? ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            if (code == (HttpStatusCode)204)
            {
                return null;
            }
            else if (code == (HttpStatusCode)201)
            {
                if (ResponseJsonOptions != null)
                    return JsonSerializer.Deserialize<Dictionary<string, object>>(payload, ResponseJsonOptions);
                else
                    return JsonSerializer.Deserialize<Dictionary<string, object>>(payload);
            }
            else if (code == (HttpStatusCode)200)
            {
                return JsonSerializer.Deserialize<Dictionary<string, object>>(payload, ResponseJsonOptions);
            }

            var payloadString = Helper.ConvertInputStreamToString(payload);

            throw new HttpResponseException(code, payloadString);
        }
    }

}