// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.

using System.Net;
using System.IO;
using System.Text.Json;
using AccelByte.Sdk.Api.Iam.Model;
using AccelByte.Sdk.Core;
using AccelByte.Sdk.Core.Util;

namespace AccelByte.Sdk.Api.Iam.Operation
{
    /// <summary>
    /// AdminGetNamespaceInvitationHistoryV4
    ///
    /// This endpoint is to Invitation Historiy for specific new studio namespace in multi tenant mode.
    /// It will return error if the service multi tenant mode is set to false.
    /// </summary>
    public class AdminGetNamespaceInvitationHistoryV4 : AccelByte.Sdk.Core.Operation
    {
        #region Builder Part
        public static AdminGetNamespaceInvitationHistoryV4Builder Builder { get => new AdminGetNamespaceInvitationHistoryV4Builder(); }

        public class AdminGetNamespaceInvitationHistoryV4Builder
            : OperationBuilder<AdminGetNamespaceInvitationHistoryV4Builder>
        {





            internal AdminGetNamespaceInvitationHistoryV4Builder() { }






            public AdminGetNamespaceInvitationHistoryV4 Build(
                string namespace_
            )
            {
                AdminGetNamespaceInvitationHistoryV4 op = new AdminGetNamespaceInvitationHistoryV4(this,
                    namespace_
                );
                op.PreferredSecurityMethod = PreferredSecurityMethod;
                op.RequestJsonOptions = RequestJsonOptions;
                op.ResponseJsonOptions = ResponseJsonOptions;
                op.FlightId = FlightId;

                return op;
            }
        }

        private AdminGetNamespaceInvitationHistoryV4(AdminGetNamespaceInvitationHistoryV4Builder builder,
            string namespace_
        )
        {
            PathParams["namespace"] = namespace_;







            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }
        #endregion

        public AdminGetNamespaceInvitationHistoryV4(
            string namespace_
        )
        {
            PathParams["namespace"] = namespace_;







            Securities.Add(AccelByte.Sdk.Core.Operation.SECURITY_BEARER);
        }

        public override string Path => "/iam/v4/admin/namespaces/{namespace}/invitationHistories";

        public override HttpMethod Method => HttpMethod.Get;

        public override string[] Consumes => new string[] { };

        public override string[] Produces => new string[] { "application/json" };

        [Obsolete("2022-04-19 - Use 'Securities' property instead.")]
        public override string? Security { get; set; } = "Bearer";

        public Model.ModelInvitationHistoryResponse? ParseResponse(HttpStatusCode code, string contentType, Stream payload)
        {
            if (code == (HttpStatusCode)204)
            {
                return null;
            }
            else if (code == (HttpStatusCode)201)
            {
                if (ResponseJsonOptions != null)
                    return JsonSerializer.Deserialize<Model.ModelInvitationHistoryResponse>(payload, ResponseJsonOptions);
                else
                    return JsonSerializer.Deserialize<Model.ModelInvitationHistoryResponse>(payload);
            }
            else if (code == (HttpStatusCode)200)
            {
                return JsonSerializer.Deserialize<Model.ModelInvitationHistoryResponse>(payload, ResponseJsonOptions);
            }

            var payloadString = Helper.ConvertInputStreamToString(payload);

            throw new HttpResponseException(code, payloadString);
        }
    }

}